config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  resources :users, only: [:new, :create]
  get '/profile', to: 'users#show'
  get 'login', to: "users#login_form"
  post '/login', to: 'users#login_user'
  delete '/logout', to: "users#logout"
  get '/edit_profile', to: "users#edit"
  patch '/profile', to: "users#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/scraped_datum.rb
class ScrapedDatum < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates_presence_of :password_digest, require: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new

  # end

  # def create
  #   user = User.find_by(email: params[:email])
  #   session[:user_id] = user.id
  #   flash[:success] = "Welcome, #{user.username}!"
  #   redirect_to '/profile'
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @user = User.find(session[:user_id])
      if current_user.id == @user.id
      else
        flash[:error] = "Only the user can view their profile."
        redirect_to root_path
      end
    else
      flash[:error] = "Only the user can view their profile."
      redirect_to root_path
    end
  end

  def new
    @user = User.new 
  end

  def create
    user = User.create(user_params)
    if user.save
      session[:user_id] = user.id 
      redirect_to profile_path(user)
    else
      flash[:error] = "Invalid credentials. Please try again."
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:format])
    if current_user.id == @user.id
      # @user = User.find(session[:user_id])
    else
      flash[:error] = "Only the user can view their profile."
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:format])
    if current_user.id == @user.id
      require 'pry'; binding.pry
      if @user.update(user_params) #&& !@user.update(user_params)
        require 'pry'; binding.pry
        # @user.update(user_params)
        current_user.update(user_params_edit) && !current_user.update(user_params)
        # require 'pry'; binding.pry
        flash[:success] = "Your profile has been updated." 
        redirect_to profile_path(@user)
        # require 'pry'; binding.pry
        # render :show
      else
        flash[:error] = "Please fill in all fields."
        redirect_to edit_profile_path(@user)
      end
    else 
      flash[:error] = "Only the user can view their profile."
    end
  end
  
  def login_form

  end

  def login_user
      user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.username}!"
      redirect_to root_path
    else
      flash[:error] = "Sorry, your credentials are bad."
      redirect_to login_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def user_params_edit
      params.permit(:username, :email)
    end
    # def user_params_edit
    #   require 'pry'; binding.pry
    #   params.require(:user).permit(:username, :email)
    # end
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NbaBettingStats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <% if current_user %>
    <%= link_to "My Dashboard", profile_path(@user, :id) %>
    <% end %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<%= form_with model: @user, url: profile_path(@user), action: :update, method: :patch, local: true do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username %>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= form.submit "Update Your Profile" %>
<% end %>

app/views/users/login_form.html.erb
<div>
<%= form_with url: login_path, method: :post do |form| %>
  <%= form.label :username, "Username:" %>
  <%= form.text_field :username %>
  <%= form.label :password, "Password:" %>
  <%= form.password_field :password %>
  <%= form.submit "Login" %>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Create a new user profile</h1>
<div>
<%= form_with model: @user, url: { controller: 'users', action: 'create' }, method: :post, local: true do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username %>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= form.label :password %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
  <%= form.submit "Create User Profile" %>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Welcome to your dashboard, <%= @user.username %>!</h1>
<h2>Your email is <%= @user.email %></h2>
<p>Need to change your profile? <%= link_to 'Edit Profile', edit_profile_path(@user) %></p>

app/views/welcome/index.html.erb
<h1>Welcome to the NBA betting stats app!</h1>
<%# link_to 'Logout', logout_path, method: :delete %>
<%# <%= link_to 'Login with Google', %> 
<% if current_user %>
  <%= button_to "Log Out", logout_path, method: :delete %>
<% else %>
  <%= link_to 'Create New User', new_user_path %>
  <%= link_to 'Login with username or email', login_path %>
<% end %>